buildVariable: false
familyName: Noto Znamenny Musical Notation
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoZnamennyMusicalNotation.glyphs
